import { TranslationMessages } from 'ra-core';

const italianMessages: TranslationMessages = {
    ra: {
        action: {
            add_filter: 'Aggiungi filtro',
            add: 'Aggiungi',
            back: 'Torna indietro',
            bulk_actions: '1 elemento selezionato |||| %{smart_count} elementi selezionati',
            cancel: 'Annulla',
            clear_array_input: 'Svuota la lista',
            clear_input_value: 'Cancella valore',
            clone: 'Clona',
            confirm: 'Conferma',
            create: 'Crea',
            create_item: 'Crea %{item}',
            delete: 'Elimina',
            edit: 'Modifica',
            export: 'Esporta',
            list: 'Elenco',
            refresh: 'Aggiorna',
            remove_filter: 'Rimuovi questo filtro',
            remove_all_filters: 'Rimuovi tutti i filtri',
            remove: 'Rimuovi',
            save: 'Salva',
            search: 'Cerca',
            select_all: 'Seleziona tutto',
            select_row: 'Seleziona questa riga',
            show: 'Mostra',
            sort: 'Ordina',
            undo: 'Annulla',
            unselect: 'Deseleziona',
            expand: 'Espandi',
            close: 'Chiudi',
            open_menu: 'Apri menu',
            close_menu: 'Chiudi menu',
            update: 'Aggiorna',
            move_up: 'Sposta su',
            move_down: 'Sposta giù',
            open: 'Apri',
            toggle_theme: 'Attiva/disattiva modalità chiaro/scuro',
            select_columns: 'Colonne',
            update_application: 'Ricarica applicazione',
        },
        boolean: {
            true: 'Sì',
            false: 'No',
            null: ' ',
        },
        page: {
            create: 'Crea %{name}',
            dashboard: 'Dashboard',
            edit: 'Modifica %{name} %{recordRepresentation}',
            error: 'Qualcosa è andato storto',
            list: '%{name}',
            loading: 'Caricamento',
            not_found: 'Non trovato',
            show: 'Mostra %{name} %{recordRepresentation}',
            empty: 'Ancora nessun %{name}.',
            invite: 'Vuoi aggiungerne uno?',
        },
        input: {
            file: {
                upload_several: 'Trascina i file per caricarli, o clicca per selezionarne uno.',
                upload_single: 'Trascina un file per caricarlo, o clicca per selezionarlo.',
            },
            image: {
                upload_several: 'Trascina le immagini per caricarle, o clicca per selezionarne una.',
                upload_single: 'Trascina un\'immagine per caricarla, o clicca per selezionarla.',
            },
            references: {
                all_missing: 'Impossibile trovare i dati di riferimento.',
                many_missing: 'Almeno uno dei riferimenti associati sembra non essere più disponibile.',
                single_missing: 'Il riferimento associato sembra non essere più disponibile.',
            },
            password: {
                toggle_visible: 'Nascondi password',
                toggle_hidden: 'Mostra password',
            },
        },
        message: {
            about: 'Informazioni',
            are_you_sure: 'Sei sicuro?',
            auth_error: 'Si è verificato un errore durante la convalida del token di autenticazione.',
            bulk_delete_content: 'Sei sicuro di voler eliminare questo %{name}? |||| Sei sicuro di voler eliminare questi %{smart_count} elementi?',
            bulk_delete_title: 'Elimina %{name} |||| Elimina %{smart_count} %{name}',
            bulk_update_content: 'Sei sicuro di voler aggiornare questo %{name}? |||| Sei sicuro di voler aggiornare questi %{smart_count} elementi?',
            bulk_update_title: 'Aggiorna %{name} |||| Aggiorna %{smart_count} %{name}',
            clear_array_input: 'Sei sicuro di voler cancellare l\'intera lista?',
            delete_content: 'Sei sicuro di voler eliminare questo elemento?',
            delete_title: 'Elimina %{name} #%{id}',
            details: 'Dettagli',
            error: "Si è verificato un errore lato client e la tua richiesta non è stata completata.",
            invalid_form: 'Il modulo non è valido. Si prega di controllare gli errori',
            loading: 'Attendere prego',
            no: 'No',
            not_found: 'O hai digitato un URL errato, o hai seguito un link errato.',
            yes: 'Sì',
            unsaved_changes: "Alcune delle tue modifiche non sono state salvate. Sei sicuro di volerle ignorare?",
        },
        navigation: {
            no_results: 'Nessun risultato trovato',
            no_more_results: 'La pagina %{page} è fuori dai limiti. Prova la pagina precedente.',
            page_out_of_boundaries: 'Il numero di pagina %{page} è fuori dai limiti',
            page_out_from_end: 'Non puoi andare oltre l\'ultima pagina',
            page_out_from_begin: 'Non puoi andare prima della pagina 1',
            page_range_info: '%{offsetBegin}-%{offsetEnd} di %{total}',
            partial_page_range_info: '%{offsetBegin}-%{offsetEnd} di più di %{offsetEnd}',
            current_page: 'Pagina %{page}',
            page: 'Vai alla pagina %{page}',
            first: 'Vai alla prima pagina',
            last: 'Vai all\'ultima pagina',
            next: 'Vai alla pagina successiva',
            previous: 'Vai alla pagina precedente',
            page_rows_per_page: 'Righe per pagina:',
            skip_nav: 'Salta al contenuto',
        },
        sort: {
            sort_by: 'Ordina per %{field} %{order}',
            ASC: 'crescente',
            DESC: 'decrescente',
        },
        auth: {
            auth_check_error: 'Effettua il login per continuare',
            user_menu: 'Profilo',
            username: 'Nome utente',
            password: 'Password',
            sign_in: 'Accedi',
            sign_in_error: 'Autenticazione fallita, riprova',
            logout: 'Esci',
        },
        notification: {
            updated: 'Elemento aggiornato |||| %{smart_count} elementi aggiornati',
            created: 'Elemento creato',
            deleted: 'Elemento eliminato |||| %{smart_count} elementi eliminati',
            bad_item: 'Elemento non corretto',
            item_doesnt_exist: "L'elemento non esiste",
            http_error: 'Errore di comunicazione con il server',
            data_provider_error: 'Errore del dataProvider. Controlla la console per i dettagli.',
            i18n_error: 'Impossibile caricare le traduzioni per la lingua specificata',
            canceled: 'Azione annullata',
            logged_out: 'La tua sessione è terminata, effettua nuovamente l\'accesso.',
            not_authorized: "Non sei autorizzato ad accedere a questa risorsa.",
            application_update_available: 'È disponibile una nuova versione.',
        },
        validation: {
            required: 'Richiesto',
            minLength: 'Deve contenere almeno %{min} caratteri',
            maxLength: 'Deve contenere al massimo %{max} caratteri',
            minValue: 'Deve essere almeno %{min}',
            maxValue: 'Deve essere al massimo %{max}',
            number: 'Deve essere un numero',
            email: 'Deve essere un\'email valida',
            oneOf: 'Deve essere uno di: %{options}',
            regex: 'Deve corrispondere a un formato specifico (regexp): %{pattern}',
            unique: 'Deve essere univoco',
        },
        saved_queries: {
            label: 'Query salvate',
            query_name: 'Nome query',
            new_label: 'Salva la query corrente...',
            new_dialog_title: 'Salva la query corrente come',
            remove_label: 'Rimuovi query salvata',
            remove_label_with_name: 'Rimuovi query "%{name}"',
            remove_dialog_title: 'Rimuovere la query salvata?',
            remove_message: 'Sei sicuro di voler rimuovere questo elemento dalla tua lista di query salvate?',
            help: 'Filtra l\'elenco e salva questa query per dopo',
        },
        configurable: {
            customize: 'Personalizza',
            configureMode: 'Configura questa pagina',
            inspector: {
                title: 'Ispettore',
                content: 'Passa sopra gli elementi dell\'interfaccia utente dell\'applicazione per configurarli',
                reset: 'Ripristina impostazioni',
                hideAll: 'Nascondi tutto',
                showAll: 'Mostra tutto',
            },
            Datagrid: {
                title: 'Datagrid',
                unlabeled: 'Colonna senza etichetta #%{column}',
            },
            SimpleForm: {
                title: 'Modulo',
                unlabeled: 'Input senza etichetta #%{input}',
            },
            SimpleList: {
                title: 'Elenco',
                primaryText: 'Testo principale',
                secondaryText: 'Testo secondario',
                tertiaryText: 'Testo terziario',
            },
        },
    },
};

export default italianMessages;
